export const pdfData = {
  generation: {
    category: "Generation",
    voltage: "13.8 kV to 24 kV",
    description: "Generating stations convert energy from coal, oil, gas, water, steam, and atoms into electrical energy. Facilities are usually located long distances from load centers.",
    bulletPoints: [
      { label: "Steam", value: "Fossil-fired, Nuclear, Geothermal, Solar" },
      { label: "Hydroelectric", value: "Uses water pressure to turn turbines" },
      { label: "Combustion", value: "Engine or turbine (similar to jet engine)" },
      { label: "Other", value: "Wind, Cogeneration, Biomass, Resource recovery" }
    ],
    details: "Electricity is generated at 13.8 kV to 24 kV. Although optimal for generation, it is too low for transmitting long distances, so it is stepped up immediately to transmission voltages."
  },
  generationTypes: {
    PowerPlant: {
      category: "Generation - Steam",
      voltage: "13.8 kV to 24 kV",
      description: "Fossil-fired generation uses coal, oil, or natural gas to boil water and create steam. The high-pressure steam drives a turbine connected to a generator.",
      bulletPoints: [
        { label: "Advantages", value: "Relatively cheap fuel, High production capacity" },
        { label: "Disadvantages", value: "Emits pollutants, Non-renewable resource" }
      ],
      details: "Historically, fossil fuels have supplied most of the world's energy supply. The raw materials used to generate power vary from facility to facility."
    },
    NuclearPlant: {
      category: "Generation - Nuclear",
      voltage: "13.8 kV to 24 kV",
      description: "Nuclear fission is accomplished by splitting the nucleus of an atom. The heat produced boils water into steam to drive a turbine.",
      bulletPoints: [
        { label: "Advantages", value: "High production capacity, No airborne pollutants" },
        { label: "Disadvantages", value: "Waste disposal, Non-renewable resource" }
      ],
      details: "Approximately 20% of today's electrical energy is produced with nuclear-fired generation facilities."
    },
    HydroDam: {
      category: "Generation - Hydroelectric",
      voltage: "13.8 kV to 24 kV",
      description: "Uses water pressure to provide mechanical motion. Falling water strikes the blades of a turbine, which turns the generator.",
      bulletPoints: [
        { label: "Advantages", value: "Low operation cost, Renewable resource, No fuel" },
        { label: "Disadvantages", value: "Cost of construction, Impact on wildlife" }
      ],
      details: "Can be located near natural waterfalls or involve the construction of a dam to store water in a reservoir."
    },
    CombustionEngine: {
      category: "Generation - Combustion",
      voltage: "13.8 kV to 24 kV",
      description: "An internal combustion engine is used to spin a generator and provide mechanical motion. Often used for peak or emergency power.",
      bulletPoints: [
        { label: "Advantages", value: "Can be located anywhere, Automatic operation" },
        { label: "Disadvantages", value: "High fuel cost and pollution, Limited capacity" }
      ],
      details: "The generator can be as simple as a 5 kW generator used on camping trips or large industrial units."
    },
    WindTurbine: {
      category: "Generation - Wind",
      voltage: "13.8 kV to 24 kV",
      description: "Wind propelled turbine generator units use natural prevailing winds to drive a large propeller connected to a generator.",
      bulletPoints: [
        { label: "Advantages", value: "Renewable resource, No fuel cost" },
        { label: "Disadvantages", value: "Wind velocity limits reliability, Construction costs" }
      ],
      details: "Often installed in large arrays known as wind farms in areas with consistent prevailing winds."
    },
    SolarFarm: {
      category: "Generation - Solar",
      voltage: "13.8 kV to 24 kV",
      description: "Solar generation uses photovoltaic cells to produce electricity directly from sunlight, or mirrors to focus energy to produce steam.",
      bulletPoints: [
        { label: "Advantages", value: "Renewable resource, Produces no pollutants" },
        { label: "Disadvantages", value: "Produces small amounts of electricity, High costs" }
      ],
      details: "Solar arrays are becoming more common as a dispersed micro-generation source connected directly to the distribution system."
    },
    Biomass: {
      category: "Generation - Biomass",
      voltage: "13.8 kV to 24 kV",
      description: "Biomass projects use the combustion of waste wood or methane generated by decaying matter in municipal landfills to produce steam.",
      bulletPoints: [
        { label: "Advantages", value: "Renewable resource, Many possible site locations" },
        { label: "Disadvantages", value: "Fuel may be seasonal, Emits pollutants" }
      ],
      details: "Resource recovery (Waste-to-Energy) facilities take municipal solid waste and burn it to produce steam for electricity."
    }
  },
  transmission: {
    category: "Transmission",
    voltage: "230 kV, 345 kV, 500 kV, 765 kV",
    description: "Transmission systems move large quantities of power over long distances at high voltages. The main objective is to deliver power with minimal loss.",
    bulletPoints: [
      { label: "Structures", value: "Wood pole, Tubular steel, Lattice type steel" },
      { label: "Insulators", value: "Porcelain or Polymer (suspension/post)" },
      { label: "Conductors", value: "Bundled aluminum conductors to increase capacity" },
      { label: "Shield Wires", value: "Provide a path to ground for lightning surges" }
    ],
    details: "Lines are recognized by large, tall structures with large aluminum conductors, spaced about 1,000 feet apart. They are interconnected in a grid overseen by reliability councils (like NERC)."
  },
  subtransmission: {
    category: "Subtransmission",
    voltage: "44 kV, 69 kV, 115 kV, 138 kV",
    description: "Subtransmission becomes necessary when medium-sized blocks of power need to be delivered to distribution substations at the load center.",
    bulletPoints: [
      { label: "Purpose", value: "Deliver power to distribution substations or large industrial customers" },
      { label: "Advantage", value: "Smaller structures than transmission, easier to install in populated areas" }
    ],
    details: "Building large transmission structures near populated areas is sometimes impractical. Subtransmission operates at a lower voltage range, allowing smaller structures while still moving significant power."
  },
  distribution: {
    category: "Distribution",
    voltage: "2 kV to 34.5 kV (Primary)",
    description: "Distribution systems deliver power directly to the customer. Lines are typically not longer than 50 miles and structures are an average of 300 feet apart.",
    bulletPoints: [
      { label: "Primary", value: "The high voltage portion of a distribution line" },
      { label: "Secondary", value: "Low voltage (120-480V) running pole-to-pole" },
      { label: "Services", value: "Low voltage running pole-to-customer" },
      { label: "Equipment", value: "Transformers, Cutouts, Reclosers, Arresters, Capacitors" }
    ],
    details: "Distribution circuits can be installed on much smaller structures than subtransmission, or installed underground. They originate at distribution substations and use protective equipment to minimize outage times."
  },
  substations: {
    category: "Substations",
    voltage: "Varies by type",
    description: "Substations are locations within the electrical system that change voltage, connect/disconnect lines, and control the flow of power.",
    bulletPoints: [
      { label: "Power Transformers", value: "Change the voltage from one level to another" },
      { label: "Circuit Breakers", value: "Connect and disconnect lines and equipment" },
      { label: "Disconnect Switches", value: "Isolate lines and equipment to be worked on" },
      { label: "Ground Grid", value: "Critical element to mitigate hazards to workers and public" }
    ],
    details: "There are four main types: Generation, Transmission, Subtransmission, and Distribution substations. They also regulate current flows, control frequency, and eliminate lightning surges."
  },
  underground: {
    category: "Underground Systems",
    voltage: "Distribution Levels",
    description: "Underground systems are popular and reliable, eliminating poles from sight and immune to high winds, ice, and trees.",
    bulletPoints: [
      { label: "Cost", value: "Approximately four times more expensive than overhead" },
      { label: "Cable", value: "Polyethylene insulation with concentric copper shield" },
      { label: "Conduit", value: "PVC pipe used to protect cables in the ground" },
      { label: "Equipment", value: "Padmounted (above-ground) or Subsurface (below-grade)" }
    ],
    details: "Many cities have passed ordinances requiring all new lines to be underground. They use enclosures, manholes, or vaults to house equipment like subsurface transformers and switchgear."
  },
  customers: {
    category: "Customers",
    voltage: "120/240V, 120/208V, 240/480V, 480V",
    description: "The end users of the electrical system. The number of customers on a circuit is determined by density, type, and circuit capability.",
    bulletPoints: [
      { label: "Residential", value: "Customer dwellings (typically 120/240V)" },
      { label: "Commercial", value: "Stores, shopping centers, medical facilities" },
      { label: "Agricultural", value: "Irrigation pumps, grain storage, dairies" },
      { label: "Industrial", value: "Large manufacturing plants, refineries" }
    ],
    details: "A single circuit might serve one industrial customer while another circuit might serve 5,000 residential customers. Some large customers use dispersed micro-generation to offset peak load costs."
  }
};

export function getPdfDataForNode(id: string, type?: string) {
  if (type && pdfData.generationTypes[type as keyof typeof pdfData.generationTypes]) {
    return pdfData.generationTypes[type as keyof typeof pdfData.generationTypes];
  }

  switch (id) {
    case 'gen': return pdfData.generationTypes.PowerPlant; // Default fallback
    case 'stepup': 
    case 'trans_sub':
    case 'dist_sub': return pdfData.substations;
    case 'tower1':
    case 'tower2': return pdfData.transmission;
    case 'sub_pole': return pdfData.subtransmission;
    case 'dist_pole1':
    case 'dist_pole2': return pdfData.distribution;
    case 'vault': return pdfData.underground;
    case 'ind_cust1':
    case 'comm_ind':
    case 'comm_cust':
    case 'farm':
    case 'res': return pdfData.customers;
    default: return null;
  }
}
